name: Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_toolchain: [nightly, nightly-2024-09-01]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install msp430-elf-gcc
        shell: bash
        run: |
          curl -LO http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/8_3_1_0/export/msp430-gcc-8.3.1.25_linux64.tar.bz2
          tar xjf msp430-gcc-8.3.1.25_linux64.tar.bz2
          echo "$GITHUB_WORKSPACE/msp430-gcc-8.3.1.25_linux64/bin" >> $GITHUB_PATH

      - name: Check msp430-elf-gcc
        shell: bash
        run: msp430-elf-gcc --version

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust_toolchain }}
          override: true
          components: rust-src

      - name: Build all examples
        if: matrix.rust_toolchain == 'nightly'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --examples --features embedded-hal-02
      
      - name: Build MSRV examples
        if: matrix.rust_toolchain == 'nightly-2024-09-01'
        shell: bash
        run: |
          for ex in examples/*.rs; do
            # Skip examples that rely on non-MSRV features 
            case "$(basename $ex)" in
              lpm0.rs)
                echo "Skipping $ex"
                ;;
              *)
                echo "Building $ex"
                cargo build --example "$(basename $ex .rs)" --features embedded-hal-02
                ;;
            esac
          done
